### ISSUE TITLE
Lectura de Azure SAT

### ISSUE THREAD

**Issue by JozhAranda** [phpcfdi/rfclinc#1]
Desde este año 2022 ya no se encuentra información de lectura para los RFC que anteriormente estaban en Azure.
Ej: https://cfdisat.blob.core.windows.net/lco?restype=container&comp=list&prefix=l_RFC_2021_08_01

¿Existe algun otra URL o una actualización a la librería?

**Comment by TheSpectroMx** [comment]
Hola @JozhAranda, desafortunadamente desde que inicio 2022 las listas pasaron a ser privadas para uso exclusivo de los PACs por lo cual no hay forma de acceder por el momento a dicha información.

Saludos
